/**
 * post-task-hook.ts — The Soul of the Memory Pipeline
 * ──────────────────────────────────────────────────────
 * Called AFTER every task completes (bug fix, feature, schema change).
 * 
 * Orchestrates the FULL AUTOMATIC LIFECYCLE:
 * 1. Runs impact analysis
 * 2. Writes structured event memory           → MEMORY_SYNCHRONIZED
 * 3. Suggests ADR if architectural change
 * 4. Triggers graph hydration                  → GRAPH_HYDRATED
 * 5. Runs governance validation                → GOVERNANCE_VALIDATED
 * 6. Marks task COMPLETE                       → COMPLETE
 * 
 * ⚡ ALL STEPS RUN AUTOMATICALLY — NO HUMAN APPROVAL NEEDED
 * 
 * Usage:
 *   npm run post-task -- --type=BUG_FIX --title="fix inventory crash" ...
 * 
 * This is the bridge between "AI did something" → "System remembers it"
 */

import path from 'path';
import fs from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { writeEvent, type MemoryEvent } from './memory-writer.js';
import {
  analyzeImpact,
  executeDocCreation,
  appendToSpiderWeb,
  printAnalysisReport,
} from './impact-analyzer.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../../../');
const DECISIONS_DIR = path.join(PROJECT_ROOT, 'app', 'ai', 'system', 'decisions');

// ────────────────────────────────────────────────
// BLAST RADIUS CALCULATOR
// ────────────────────────────────────────────────
const BLAST_RADIUS_MAP: Record<string, string[]> = {
  finance:     ['finance-reconciliation', 'payment-api', 'invoice-generation', 'accounting-reports'],
  inventory:   ['inventory-stock-calculation', 'product-roll-status', 'order-reservation', 'qr-scanner'],
  orders:      ['order-status-machine', 'inventory-reservation', 'shipping-creation', 'payment-trigger'],
  shipping:    ['driver-assignment', 'delivery-tracking', 'order-completion-flow'],
  drivers:     ['shift-management', 'vehicle-assignment', 'gps-tracking', 'ocr-audit'],
  procurement: ['material-stock', 'production-order-readiness'],
  production:  ['product-roll-creation', 'inventory-addition'],
  auth:        ['all-protected-routes', 'role-based-access', 'firebase-token-validation'],
  infra:       ['frontend-backend-communication', 'all-api-calls', 'realtime-socket-events'],
  schema:      ['prisma-enum-mapping', 'all-queries-touching-changed-model', 'graph-hydration-required'],
};

function calculateBlastRadius(domains: string[], affectedFiles: string[]): string[] {
  const radius = new Set<string>();
  
  for (const domain of domains) {
    (BLAST_RADIUS_MAP[domain] || []).forEach(r => radius.add(r));
  }
  
  // Schema change = special blast radius
  if (affectedFiles.some(f => f.includes('schema.prisma'))) {
    (BLAST_RADIUS_MAP.schema || []).forEach(r => radius.add(r));
  }
  
  return Array.from(radius);
}

// ────────────────────────────────────────────────
// ADR SUGGESTION ENGINE
// ────────────────────────────────────────────────
const ARCHITECTURAL_TRIGGERS = [
  { pattern: /schema\.prisma/i, reason: 'DB schema changed' },
  { pattern: /vite\.config/i, reason: 'Build/proxy configuration changed' },
  { pattern: /middleware/i, reason: 'Auth/middleware layer changed' },
  { pattern: /prisma.*transaction|\$transaction/i, reason: 'Transaction boundary changed' },
  { pattern: /socket\.io|io\.emit/i, reason: 'Real-time event protocol changed' },
  { pattern: /routes\/index|router\.use/i, reason: 'API routing structure changed' },
];

function suggestADR(affectedFiles: string[], domains: string[]): string | null {
  // Check if any file matches architectural trigger patterns
  for (const { pattern, reason } of ARCHITECTURAL_TRIGGERS) {
    if (affectedFiles.some(f => pattern.test(f))) {
      return reason;
    }
  }
  
  // Finance/inventory core changes always warrant ADR consideration
  if (domains.includes('finance') || domains.some(d => 
    ['auth', 'infra'].includes(d)
  )) {
    return `Core ${domains[0]} domain behavior changed`;
  }
  
  return null;
}

function getNextADRNumber(): number {
  if (!fs.existsSync(DECISIONS_DIR)) return 16;
  const adrFiles = fs.readdirSync(DECISIONS_DIR).filter(f => f.startsWith('ADR-'));
  if (adrFiles.length === 0) return 16;
  const numbers = adrFiles.map(f => parseInt(f.replace('ADR-', '').split('-')[0])).filter(n => !isNaN(n));
  return Math.max(...numbers) + 1;
}

function generateADRDraft(adrNumber: number, title: string, domains: string[], why: string, solution: string): string {
  const content = `# ADR-${String(adrNumber).padStart(3, '0')}: ${title}

**Date:** ${new Date().toISOString().split('T')[0]}
**Status:** DRAFT — Awaiting review
**Domain:** ${domains.join(', ')}

---

## Context

[Describe the situation that led to this decision]

## Problem

${why}

## Decision

${solution}

## Consequences

✅ [Positive outcomes]
⚠️ [Trade-offs or risks]

## Files Changed

[List relevant files]

---
*Auto-generated by post-task-hook.ts — Edit to add full context*
`;
  const filename = `ADR-${String(adrNumber).padStart(3, '0')}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}.md`;
  const filepath = path.join(DECISIONS_DIR, filename);
  fs.mkdirSync(DECISIONS_DIR, { recursive: true });
  fs.writeFileSync(filepath, content, 'utf-8');
  return filename;
}

// ────────────────────────────────────────────────
// GRAPH HYDRATION TRIGGER (INCREMENTAL)
// ────────────────────────────────────────────────
function triggerIncrementalHydration(eventPath: string): boolean {
  const graphEnginePath = path.join(PROJECT_ROOT, 'app', 'ai', 'graph-engine');
  console.log(`[PostTaskHook] 💧 Triggering incremental graph hydration...`);
  try {
    execSync(`npx tsx src/incremental-hydrate.ts "${eventPath}"`, {
      cwd: graphEnginePath,
      stdio: 'inherit',
    });
    console.log(`[PostTaskHook] ✅ GRAPH_HYDRATED`);
    return true;
  } catch (e) {
    console.warn(`[PostTaskHook] ⚠️ Incremental hydration failed (non-blocking):`, e);
    return false;
  }
}

// ────────────────────────────────────────────────
// GOVERNANCE VALIDATION (AUTOMATIC — NO HUMAN APPROVAL)
// ────────────────────────────────────────────────
function runGovernanceValidation(eventPath: string, domains: string[]): boolean {
  console.log(`\n[GovernanceValidator] 🛡️  Running automatic governance validation...`);
  
  let eventData: any;
  try {
    eventData = JSON.parse(fs.readFileSync(eventPath, 'utf-8'));
  } catch (e) {
    console.error(`[GovernanceValidator] ❌ Cannot parse event: ${eventPath}`);
    return false;
  }

  const errors: string[] = [];

  // 1. Required fields
  const requiredFields = ['why', 'root_cause', 'blast_radius', 'prevention'];
  for (const field of requiredFields) {
    const val = eventData[field];
    if (!val) {
      errors.push(`Missing required field: '${field}'`);
    } else if (typeof val === 'string' && val.length < 15) {
      errors.push(`Field '${field}' is too short (must be >= 15 chars)`);
    }
  }

  // 2. Blast radius enforcement
  if (!eventData.blast_radius || eventData.blast_radius.length === 0) {
    errors.push(`'blast_radius' array cannot be empty`);
  }

  // 3. Critical domain checks
  const isCritical = domains.some(d => ['finance', 'inventory', 'orders'].includes(d));
  if (isCritical) {
    if (!eventData.rollback_strategy || eventData.rollback_strategy.length < 15) {
      errors.push(`Critical domain requires valid 'rollback_strategy'`);
    }
    if (eventData.governance_approval !== true) {
      errors.push(`Critical domain requires 'governance_approval: true'`);
    }
  }

  // 4. ENGINEERING_LOG synchronization
  const logPath = path.join(PROJECT_ROOT, 'ENGINEERING_LOG.md');
  if (fs.existsSync(logPath)) {
    const logContent = fs.readFileSync(logPath, 'utf-8');
    const titleSlug = (eventData.title || '').substring(0, 30);
    if (!logContent.includes(eventData.event_id) && !logContent.includes(titleSlug)) {
      errors.push(`ENGINEERING_LOG.md not synchronized with event ${eventData.event_id}`);
    }
  }

  // Report
  if (errors.length > 0) {
    console.error(`[GovernanceValidator] ❌ FAILED (${errors.length} issues):`);
    errors.forEach(err => console.error(`  - ${err}`));
    console.error(`[GovernanceValidator] ⚠️  Fix the event file: ${eventPath}`);
    return false;
  }

  console.log(`[GovernanceValidator] ✅ GOVERNANCE_VALIDATED`);
  console.log(`  ✓ Required fields present`);
  console.log(`  ✓ Blast radius: ${eventData.blast_radius.length} items`);
  console.log(`  ✓ ENGINEERING_LOG: synchronized`);
  if (isCritical) {
    console.log(`  ✓ Critical domain: rollback_strategy + governance_approval OK`);
  }
  return true;
}

// ────────────────────────────────────────────────
// MAIN POST-TASK HOOK
// ────────────────────────────────────────────────
export interface PostTaskInput {
  type: MemoryEvent['type'];
  title: string;
  why: string;
  root_cause: string;
  solution: string;
  affected_files: string[];
  affected_domains: string[];
  affected_nodes?: string[];
  severity?: MemoryEvent['severity'];
  caused_by?: string[];
  related_incidents?: string[];
  prevention?: string;
  rollback_strategy?: string;
  governance_approval?: boolean;
  data_loss?: boolean;
  data_loss_note?: string;
  skip_hydration?: boolean;
}

export async function runPostTaskHook(input: PostTaskInput): Promise<{
  event_path: string;
  adr_created: string | null;
  hydration_triggered: boolean;
  governance_passed: boolean;
  docs_created: string[];
  impact_case: string;
}> {
  console.log(`\n[PostTaskHook] 🔄 Running memory pipeline for: "${input.title}"`);

  // ── Step 1: Run Impact Analysis (3-case classification) ──
  const analysis = analyzeImpact({
    title: input.title,
    type: input.type,
    affectedFiles: input.affected_files,
    affectedDomains: input.affected_domains,
    why: input.why,
    solution: input.solution,
    severity: input.severity,
  });

  printAnalysisReport(analysis, input.title);

  // ── Step 2: Calculate blast radius from analysis ──
  const blast_radius = calculateBlastRadius(input.affected_domains, input.affected_files);

  // ── Step 3: Write structured event (always) ──
  const event: MemoryEvent = {
    type: input.type,
    severity: analysis.severity,
    title: input.title,
    why: input.why,
    root_cause: input.root_cause,
    solution: input.solution,
    blast_radius,
    affected_files: input.affected_files,
    affected_nodes: input.affected_nodes,
    affected_domains: input.affected_domains,
    caused_by: input.caused_by,
    related_incidents: input.related_incidents,
    prevention: input.prevention,
    rollback_strategy: input.rollback_strategy,
    governance_approval: input.governance_approval,
    data_loss: input.data_loss,
    data_loss_note: input.data_loss_note,
  };

  const eventPath = writeEvent(event);
  console.log(`[PostTaskHook] ✅ MEMORY_SYNCHRONIZED`);

  // ── Step 4: ADR Engine (Check if architectural) ──
  let adrCreated: string | null = null;
  const adrReason = suggestADR(input.affected_files, input.affected_domains);
  if (adrReason && analysis.actions.createADR) {
    const nextNum = getNextADRNumber();
    adrCreated = generateADRDraft(nextNum, input.title, input.affected_domains, input.why, input.solution);
    console.log(`[PostTaskHook] 🏗️  ADR Generated: ${adrCreated} (Reason: ${adrReason})`);
  }

  // ── Step 5: Spider Web Knowledge Update (Case 2 & 3) ──
  let docsCreated: string[] = [];
  if (analysis.actions.updateSpiderWeb) {
    console.log(`[PostTaskHook] 🕸️  Updating Spider Web Knowledge...`);
    appendToSpiderWeb(input.title, input.affected_domains, analysis.reason);
    console.log(`[PostTaskHook] ✅ SPIDER_WEB_UPDATED`);
  }
  
  if (analysis.actions.createFlowDoc && analysis.actions.newDocSuggestions.length > 0) {
    console.log(`[PostTaskHook] 📄  Creating missing flow docs...`);
    const paths = executeDocCreation(analysis.actions.newDocSuggestions);
    docsCreated.push(...paths);
  }

  // ── Step 6: Graph Hydration ──
  let hydrationTriggered = false;
  if (!input.skip_hydration) {
    hydrationTriggered = triggerIncrementalHydration(eventPath);
  }

  // ── Step 7: Governance Check ──
  const governancePassed = runGovernanceValidation(eventPath, input.affected_domains);

  console.log(`\n[PostTaskHook] 🎉 Task Lifecycle COMPLETE`);
  console.log(`--------------------------------------------------`);
  console.log(`- Impact Case:    ${analysis.impactCase}`);
  console.log(`- Memory Event:   ${eventPath}`);
  console.log(`- ADR Created:    ${adrCreated || 'none'}`);
  console.log(`- Docs Updated:   ${docsCreated.length > 0 ? docsCreated.join(', ') : 'none'}`);
  console.log(`- Graph Hydrated: ${hydrationTriggered}`);
  console.log(`- Gov Passed:     ${governancePassed}`);
  console.log(`--------------------------------------------------\n`);

  return {
    event_path: eventPath,
    adr_created: adrCreated,
    hydration_triggered: hydrationTriggered,
    governance_passed: governancePassed,
    docs_created: docsCreated,
    impact_case: analysis.impactCase,
  };
}

// ────────────────────────────────────────────────
// CLI ENTRY POINT
// ────────────────────────────────────────────────
import { parseArgs } from 'util';

if (import.meta.url === `file://${process.argv[1]}` || process.argv[1].endsWith('post-task-hook.ts')) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      type: { type: 'string' },
      title: { type: 'string' },
      why: { type: 'string' },
      root_cause: { type: 'string' },
      solution: { type: 'string' },
      files: { type: 'string' },
      domains: { type: 'string' },
      nodes: { type: 'string' },
      severity: { type: 'string' },
      caused_by: { type: 'string' },
      related_incidents: { type: 'string' },
      prevention: { type: 'string' },
      rollback_strategy: { type: 'string' },
      governance_approval: { type: 'boolean' },
      data_loss: { type: 'boolean' },
      data_loss_note: { type: 'string' },
      skip_hydration: { type: 'boolean' },
    },
    strict: false,
  });

  if (!values.type || !values.title || !values.domains || !values.files) {
    console.error("Usage: tsx post-task-hook.ts --type=BUG_FIX --title='...' --domains='...' --files='...'");
    process.exit(1);
  }

  runPostTaskHook({
    type: values.type as MemoryEvent['type'],
    title: values.title as string,
    why: values.why as string || 'Not provided',
    root_cause: values.root_cause as string || 'Not provided',
    solution: values.solution as string || 'Not provided',
    affected_files: (values.files as string).split(',').map(s => s.trim()),
    affected_domains: (values.domains as string).split(',').map(s => s.trim()),
    affected_nodes: values.nodes ? (values.nodes as string).split(',').map(s => s.trim()) : undefined,
    severity: values.severity as MemoryEvent['severity'],
    caused_by: values.caused_by ? (values.caused_by as string).split(',').map(s => s.trim()) : undefined,
    related_incidents: values.related_incidents ? (values.related_incidents as string).split(',').map(s => s.trim()) : undefined,
    prevention: values.prevention as string,
    rollback_strategy: values.rollback_strategy as string,
    governance_approval: values.governance_approval === true || values.governance_approval === 'true',
    data_loss: values.data_loss === true || values.data_loss === 'true',
    data_loss_note: values.data_loss_note as string,
    skip_hydration: values.skip_hydration as boolean,
  }).catch(err => {
    console.error("Failed to run post task hook:", err);
    process.exit(1);
  });
}